baseURL = "https://alexn.eu"
title = "alexn.eu"
theme = "PaperMod"
publishDir = "docs"

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
# category = "categories"
tag = "tags"
# series = "series"

[[languages.en.menu.main]]
name = "tags"
url = "tags/"
weight = 100

[params]
custom_css = ["css/custom.css"]
custom_js = []

socialIcons = [
    { name = "github", url = "https://github.com/aleneum" },
    { name = "stackoverflow", url = "https://stackoverflow.com/users/1617563/aleneum"},
    { name = "twitter", url = "https://twitter.com/fuffzehnzeichen" },
    { name = "codepen", url = "https://codepen.io/aleneum"},
    { name = "youtube",  url = "https://www.youtube.com/channel/UCnb4zOgjZ1ojkLWBGWJeYRA"},
    { name = "linkedin", url = "https://www.linkedin.com/in/alexander-neumann-9288a724/"},
    { name = "orcid", url= "https://orcid.org/0000-0002-2190-5576"},
    { name = "email", url= "mailto:aleneum@gmail.com"}
]

ShowCodeCopyButtons = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[params.editPost]
URL =  "https://github.com/aleneum/aleneum.github.io/tree/main/content"
text = "Suggest Changes" # edit text
appendFilePath = true # to append file path to Edit link

[params.homeInfoParams]
title = "Towards smart things and smarter people"
content = "A blog about research and development work"

[markup.goldmark.renderer]
unsafe = true
